// AUTO GENERATED BY REACT NATIVE TESTIFY. DO NOT EDIT.

function loadScreenshotTests() {
  require('./components/Badge/Badge.screenshots');
  require('./components/Box/Box.screenshots');
}

function loadScreenshotTestsIfInDevMode() {
  if (__DEV__) {
    loadScreenshotTests();
  }
}

module.exports = loadScreenshotTestsIfInDevMode;
